### ISSUE TITLE
zoom in/out feature not included in the latest package

### ISSUE THREAD

**Issue by diwashbiswa** [microsoft/CanvasTools-for-VOTT#110]
1. npm package version for canvas tools doesn't include the zoom in/out feature
2. Zoom Manager and other essential tools for zooming in/out missing
3. Is Editor w/ Zoom feature not available in version - "vott-ct": "^2.2.25"?

**Comment by pritamDas9191** [comment]
Zoom feature has been available from 2.2.4 onwards.
