### ISSUE TITLE
Disabled keyboard events

### ISSUE THREAD

**Issue by maverick136** [microsoft/CanvasTools-for-VOTT#125]
Is it possible to disable the keyboard events?

**Comment by kichinsky** [comment]
You should be able to a custom ToolbarIconDescription for the CanvasTools.Editor. 

Just set empty array for `key:`
`{
            type: ToolbarItemType.SELECTOR,
            action: "none-select",
            iconFile: "none-selection.svg",
            tooltip: "Regions Manipulation (M)",
            key: ["M", "m"],
            actionCallback: (action, rm, sl) => {
                sl.setSelectionMode({ mode: SelectionMode.NONE });
            },
            activate: false,
        },`

Than you can pass a custom toolbar description when you add toolbar:
`editor.addToolbar(toolbarContainer, **CanvasTools.Editor.RectToolbarSet**, "./../shared/media/icons/");`

**Comment by maverick136** [comment]
thanks!
