### ISSUE TITLE
Issues running the samples on Chrome 

### ISSUE THREAD

**Issue by cedricve** [microsoft/CanvasTools-for-VOTT#62]
Hello, Amazing library!

I'm having issues visualising the background image, and the toolbar is not shown completely anymore using latest chrome.

Any idea?

Cédric

<img width="832" alt="Screenshot 2019-05-10 at 16 47 00" src="https://user-images.githubusercontent.com/1546779/57539834-40486480-7343-11e9-8be4-7d8730aba591.png">

**Comment by kichinsky** [comment]
Nope, what is the latest Chrome version? Are there any issues in console (through dev tools)?

**Comment by cedricve** [comment]
hmm no issues in console, i can confirm my chrome version later today. But I just tried out the sample, so it's easy to reproduce.  thanks

**Comment by cedricve** [comment]
Version 74.0.3729.131 (Official Build) (64-bit)
