### ISSUE TITLE
Error when calling addRegion with null tag descriptor

### ISSUE THREAD

**Issue by series8217** [microsoft/CanvasTools-for-VOTT#89]
Unless I'm missing something, it should be safe to just not announce if tagDescriptor is null, then announce later when one of the updateTags methods is called.

![image](https://user-images.githubusercontent.com/5247558/85791234-57344c80-b6e6-11ea-8936-01631dc41a30.png)

**Comment by soyfestivo** [comment]
You're correct. This was a bug that has been fixed in `2.2.17` and onward.
